// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3EJZWzgazgUsHnWA6GKhUxCACh1XPHIk',
    appId: '1:1081014542858:web:0c4a9491a550a102dbb5f3',
    messagingSenderId: '1081014542858',
    projectId: 'socialmediaapp-519b1',
    authDomain: 'socialmediaapp-519b1.firebaseapp.com',
    storageBucket: 'socialmediaapp-519b1.appspot.com',
    measurementId: 'G-RHSB9EQTH7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZPq04v8fCVaspm3_q-5whoBcEqF-f5BM',
    appId: '1:1081014542858:android:fabdc8192a9fc7d3dbb5f3',
    messagingSenderId: '1081014542858',
    projectId: 'socialmediaapp-519b1',
    storageBucket: 'socialmediaapp-519b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0mJIG7rV0xEoicWLixu6Y8FUjrufZKSc',
    appId: '1:1081014542858:ios:cc8b9b37710102f5dbb5f3',
    messagingSenderId: '1081014542858',
    projectId: 'socialmediaapp-519b1',
    storageBucket: 'socialmediaapp-519b1.appspot.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0mJIG7rV0xEoicWLixu6Y8FUjrufZKSc',
    appId: '1:1081014542858:ios:cc8b9b37710102f5dbb5f3',
    messagingSenderId: '1081014542858',
    projectId: 'socialmediaapp-519b1',
    storageBucket: 'socialmediaapp-519b1.appspot.com',
    iosBundleId: 'com.example.socialMediaApp',
  );
}
